/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2025-05-23 01:46:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class destinationdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_2;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:escapeXml", org.apache.taglibs.standard.functions.Functions.class, "escapeXml", new Class[] {java.lang.String.class});
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
  _jspx_fnmap_2= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:split", org.apache.taglibs.standard.functions.Functions.class, "split", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1745564312942L));
    _jspx_dependants.put("jar:file:/D:/midProject_wk/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tripin/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/midProject_wk/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tripin/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Tripin - 여행지 상세</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- 공통 CSS: Tailwind + 외부 css -->\r\n");
      out.write("\r\n");
      out.write("  <!-- 외부 CSS -->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/destinationdetail.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- 구글 폰트 -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Pacifico&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- 아이콘 -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.6.0/remixicon.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- jQuery -->\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- 외부 JS -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/destinationdetail.js\" defer></script>\r\n");
      out.write("  \r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com/3.4.16\"></script>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("  <script>\r\n");
      out.write("    tailwind.config = {\r\n");
      out.write("      theme: {\r\n");
      out.write("        extend: {\r\n");
      out.write("          colors: {\r\n");
      out.write("            primary: '#4F46E5',\r\n");
      out.write("            secondary: '#10B981'\r\n");
      out.write("          },\r\n");
      out.write("          borderRadius: {\r\n");
      out.write("            'none': '0px',\r\n");
      out.write("            'sm': '4px',\r\n");
      out.write("            DEFAULT: '8px',\r\n");
      out.write("            'md': '12px',\r\n");
      out.write("            'lg': '16px',\r\n");
      out.write("            'xl': '20px',\r\n");
      out.write("            '2xl': '24px',\r\n");
      out.write("            '3xl': '32px',\r\n");
      out.write("            'full': '9999px',\r\n");
      out.write("            'button': '8px'\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-white font-['Noto Sans KR']\"\r\n");
      out.write("      data-name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(name)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" data-contentid=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(contentId)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" data-context-path=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"    data-login-user-id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUserId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("  <!-- ✅ 상단 고정 네비게이션 -->\r\n");
      out.write("   <header class=\"bg-white shadow-sm sticky top-0 z-50\">\r\n");
      out.write("        <div class=\"container mx-auto px-4 py-3 flex items-center justify-between\">\r\n");
      out.write("            <div class=\"flex items-center\">\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mainpage\" class=\"font-['Pacifico'] text-primary text-2xl\">Tripin</a>\r\n");
      out.write("                <nav class=\"ml-8 hidden md:flex\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mainpage\" \r\n");
      out.write("   class=\"px-4 py-2 text-gray-700 font-medium \"> 홈</a>\r\n");
      out.write("                    <a href=\"#\" class=\"px-4 py-2 text-gray-700 hover:text-primary font-medium\">트리비와 대화하기</a>\r\n");
      out.write("                    <a href=\"#\" class=\"px-4 py-2 text-gray-700 hover:text-primary font-medium\">테마여행</a>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/destinationdetail\" class=\"px-4 py-2 text-primary hover:text-primary font-semibold border-b-2 border-primary hover:text-primary\">여행지 상세</a>\r\n");
      out.write("              \r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"flex items-center space-x-4\">\r\n");
      out.write("                <div class=\"relative hidden md:block\">\r\n");
      out.write("                    <input type=\"text\" class=\"search-input bg-gray-100 pl-10 pr-4 py-2 rounded-full text-sm border-none w-64\" placeholder=\"여행지, 테마 검색\">\r\n");
      out.write("                    <div class=\"absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 flex items-center justify-center text-gray-500\">\r\n");
      out.write("                        <i class=\"ri-search-line\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"#\" class=\"text-gray-700 hover:text-primary\">\r\n");
      out.write("                    <div class=\"w-10 h-10 flex items-center justify-center\">\r\n");
      out.write("                        <i class=\"ri-user-line ri-lg\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <button class=\"bg-primary text-white px-4 py-2 !rounded-button whitespace-nowrap hidden md:block\">로그인</button>\r\n");
      out.write("                <div class=\"w-10 h-10 flex items-center justify-center md:hidden text-gray-700\">\r\n");
      out.write("                    <i class=\"ri-menu-line ri-lg\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("  <!-- ✅ 메인 검색 화면 -->\r\n");
      out.write("  <section id=\"searchSection\" class=\"relative z-10 flex flex-col items-center justify-center h-screen\">\r\n");
      out.write("    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sky1.jpg\" alt=\"배경 이미지\" class=\"absolute inset-0 w-full h-full object-cover z-0\" />\r\n");
      out.write("    <div class=\"absolute inset-0 bg-white/40 backdrop-blur-sm z-0\"></div>\r\n");
      out.write("\r\n");
      out.write("    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/tripin_logo.png\" alt=\"Tripin 로고\" class=\"w-[300px] mb-10 z-10\" />\r\n");
      out.write("    <div class=\"relative w-full max-w-[900px] z-10\">\r\n");
      out.write("      <input id=\"mainSearch\" type=\"text\" placeholder=\"상세 여행지를 입력하세요.\" class=\"w-full px-8 py-5 text-xl border border-gray-300 rounded-full shadow text-center focus:outline-none focus:ring-2 focus:ring-primary pr-16\" />\r\n");
      out.write("      <button id=\"searchBtn\" class=\"absolute right-4 top-1/2 transform -translate-y-1/2 text-gray-500 hover:text-primary\">\r\n");
      out.write("        <i class=\"ri-search-line text-2xl\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"mt-8 flex flex-wrap justify-center gap-4 z-10\">\r\n");
      out.write("      <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#경복궁</a>\r\n");
      out.write("      <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#제주도</a>\r\n");
      out.write("      <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#해운대</a>\r\n");
      out.write("      <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#남산타워</a>\r\n");
      out.write("      <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#전주한옥마을</a>\r\n");
      out.write("      <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#강릉</a>\r\n");
      out.write("      <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#속초</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <!-- ✅ 여행지 상세 화면 (숨겨진 영역, JS로 전환) -->\r\n");
      out.write(" \r\n");
      out.write("  <section id=\"detailSection\" class=\"w-full bg-white py-12 hidden\">\r\n");
      out.write(" <div class=\"max-w-screen-lg mx-auto px-4 relative\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"mt-24 mb-12 text-center space-y-4 -translate-y-16\">\r\n");
      out.write("  <!-- 검색창 -->\r\n");
      out.write("  <div class=\"relative w-full mt-20\">\r\n");
      out.write("    <input id=\"mainSearch\" type=\"text\" placeholder=\"상세 여행지를 입력하세요.\"\r\n");
      out.write("      class=\"w-full px-8 py-5 text-xl border border-gray-300 rounded-full shadow text-center focus:outline-none focus:ring-2 focus:ring-primary pr-16 bg-white\" />\r\n");
      out.write("    <button id=\"searchBtn\"\r\n");
      out.write("      class=\"absolute right-4 top-1/2 transform -translate-y-1/2 text-gray-500 hover:text-primary\">\r\n");
      out.write("      <i class=\"ri-search-line text-2xl\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- ✅ 해시태그도 같이 안에 포함 (relative 아님) -->\r\n");
      out.write("  <div class=\"!mt-16 flex flex-wrap justify-center gap-3\">\r\n");
      out.write("    <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#광주</a>\r\n");
      out.write("    <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#경복궁</a>\r\n");
      out.write("    <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#제주도</a>\r\n");
      out.write("    <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#해운대</a>\r\n");
      out.write("    <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#남산타워</a>\r\n");
      out.write("    <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#전주한옥마을</a>\r\n");
      out.write("    <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#강릉</a>\r\n");
      out.write("    <a href=\"#\" class=\"px-5 py-2 bg-primary text-white rounded-full hover:bg-primary/90\">#속초</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 상단 탭 배너 -->\r\n");
      out.write("<div class=\"w-full border-b border-gray-300 mb-8\">\r\n");
      out.write("  <div class=\"grid grid-cols-3 text-center text-lg font-medium text-gray-600\">\r\n");
      out.write("    \r\n");
      out.write("    <button onclick=\"scrollToSection('infoSection')\" id=\"tab-info\"\r\n");
      out.write("      class=\"py-3 tab-btn-style border-b-2 border-black text-black font-bold\">\r\n");
      out.write("      여행지 위치\r\n");
      out.write("    </button>\r\n");
      out.write("    \r\n");
      out.write("    <button onclick=\"scrollToSection('reviewList')\" id=\"tab-review\"\r\n");
      out.write("      class=\"py-3 tab-btn-style border-l border-r border-gray-300 hover:text-primary\">\r\n");
      out.write("      여행지 후기\r\n");
      out.write("    </button>\r\n");
      out.write("    \r\n");
      out.write("    <button onclick=\"scrollToSection('revwriteSection')\" id=\"tab-revwrite\"\r\n");
      out.write("      class=\"py-3 tab-btn-style hover:text-primary\">\r\n");
      out.write("      리뷰작성\r\n");
      out.write("    </button>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ⭐ 이미지 + 지도 -->\r\n");
      out.write("   <!-- 📸 사진 (지도 영역까지 확장) -->\r\n");
      out.write("<div class=\"w-full h-[600px] rounded-xl shadow overflow-hidden mb-10\">\r\n");
      out.write("  <div id=\"mainImageSlider\" class=\"flex transition-transform duration-500 ease-in-out\">\r\n");
      out.write("    <img src=\"https://images.unsplash.com/photo-1684042229029-8a899193a8e4\" class=\"main-photo w-full h-full object-cover snap-center cursor-pointer\" />\r\n");
      out.write("    <img src=\"https://plus.unsplash.com/premium_photo-1661886323367-fc6579695eba?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D\" class=\"main-photo w-full h-full object-cover snap-center cursor-pointer\" />\r\n");
      out.write("    <img src=\"/resources/images/trip3.jpg\" class=\"main-photo w-full h-full object-cover snap-center cursor-pointer\" />\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 📝 설명 + 탭 -->\r\n");
      out.write("<div class=\"space-y-4 mb-12\">\r\n");
      out.write("  <div class=\"flex items-center gap-2\">\r\n");
      out.write("    <h2 class=\"text-3xl font-bold text-gray-900\">tour api</h2>\r\n");
      out.write("    <button id=\"likeBtn\" class=\"text-red-500 hover:text-red-600 text-2xl leading-none focus:outline-none\">\r\n");
      out.write("      <i id=\"likeIcon\" class=\"ri-heart-line align-middle\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div id = \"infoSection\" class=\"flex items-center text-yellow-400 text-xl\">\r\n");
      out.write("    <i class=\"ri-star-fill\"></i><i class=\"ri-star-fill\"></i><i class=\"ri-star-fill\"></i><i class=\"ri-star-fill\"></i><i class=\"ri-star-half-fill\"></i>\r\n");
      out.write("    <span class=\"ml-2 text-sm text-gray-600 font-semibold\">4.5</span>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"flex space-x-6 border-b text-sm font-medium pb-4\">\r\n");
      out.write("    <button class=\"tab-btn text-gray-500 hover:text-primary\" data-tab=\"info\">기본정보</button>\r\n");
      out.write("    <button class=\"tab-btn text-gray-500 hover:text-primary\" data-tab=\"guide\">이용안내</button>\r\n");
      out.write("    <button class=\"tab-btn text-gray-500 hover:text-primary\" data-tab=\"detail\">상세정보</button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"bg-gray-50 border rounded-lg p-4 h-48 overflow-y-auto text-sm text-gray-700\">\r\n");
      out.write("    <div id=\"tab-info\" class=\"tab-content block\">나중에 tour api에서 불러올 정보</div>\r\n");
      out.write("    <div id=\"tab-guide\" class=\"tab-content hidden\">운영시간 등 안내 정보</div>\r\n");
      out.write("    <div id=\"tab-detail\" class=\"tab-content hidden\">세부 정보</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 🗺️ 지도 -->\r\n");
      out.write("<div class=\"rounded-xl shadow overflow-hidden w-full h-[400px] mt-8 mb-24\">\r\n");
      out.write("  <iframe src=\"https://www.google.com/maps?q=경포대&output=embed\"\r\n");
      out.write("          width=\"100%\" height=\"100%\" style=\"border:0;\" allowfullscreen loading=\"lazy\"\r\n");
      out.write("          referrerpolicy=\"no-referrer-when-downgrade\"></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"mt-16 mb-6\">\r\n");
      out.write("  <div class=\"flex items-center justify-between mb-3\">\r\n");
      out.write("    <h3 class=\"text-2xl font-bold text-gray-800\">\r\n");
      out.write("      여행지 후기\r\n");
      out.write("    </h3>\r\n");
      out.write("\r\n");
      out.write("    <!-- 정렬 버튼 -->\r\n");
      out.write("    <div class=\"flex gap-2\">\r\n");
      out.write("      <button class=\"sort-btn px-3 py-1 border rounded-full text-sm text-gray-600 hover:bg-primary hover:text-white transition\"\r\n");
      out.write("              data-sort=\"lastest\">최신순</button>\r\n");
      out.write("      <button class=\"sort-btn px-3 py-1 border rounded-full text-sm text-gray-600 hover:bg-primary hover:text-white transition\"\r\n");
      out.write("              data-sort=\"rating\">별점순</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 분리된 줄 -->\r\n");
      out.write(" <div class=\"border-t border-gray-200 w-full\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ⭐ 리뷰 목록 + 댓글 작성 -->\r\n");
      out.write("   <!-- 리뷰 반복 출력 -->\r\n");
      out.write("<!-- ⭐ 리뷰 목록 -->\r\n");
      out.write("<div id=\"reviewList\" class=\"mt-24 space-y-10\">\r\n");
      out.write("  ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 리뷰 작성 폼 -->\r\n");
      out.write("<form id=\"reviewForm\" method=\"post\" enctype=\"multipart/form-data\" class=\"text-sm mt-8\" >\r\n");
      out.write("  <div class=\"bg-white rounded-xl p-6 space-y-4 shadow-sm border border-gray-200\">\r\n");
      out.write("\r\n");
      out.write("    <!-- ✅ 작성자 -->\r\n");
      out.write("    <div class=\"flex items-center gap-2\">\r\n");
      out.write("      <span class=\"w-20 text-sm text-gray-600 font-medium\">작성자</span>\r\n");
      out.write("      <span class=\"text-sm font-semibold text-gray-800\">회원1</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ✅ 숨겨진 필드들 -->\r\n");
      out.write("    <input type=\"hidden\" name=\"userId\" value=\"0\" /> <!-- 임시 사용자 ID (세션에서 추후 대체) -->\r\n");
      out.write("    <input type=\"hidden\" name=\"destId\" value=\"0\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- ⭐ 별점 -->\r\n");
      out.write("    <div id=\"starRating\">\r\n");
      out.write("      <div class=\"base\">\r\n");
      out.write("        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"starOverlay\">\r\n");
      out.write("        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("        <i class=\"ri-star-fill\"></i>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"flex items-center gap-2\">\r\n");
      out.write("      <label for=\"ratingInput\" class=\"text-sm text-gray-700\">별점 :</label>\r\n");
      out.write("      <input\r\n");
      out.write("  type=\"number\"\r\n");
      out.write("  id=\"ratingInput\"\r\n");
      out.write("  name=\"rating\"\r\n");
      out.write("  min=\"0\"\r\n");
      out.write("  max=\"5\"\r\n");
      out.write("  step=\"0.5\"\r\n");
      out.write("  value=\"0\"\r\n");
      out.write("  class=\"w-16 border border-gray-300 rounded px-2 py-1 text-sm text-right\"\r\n");
      out.write("/>		\r\n");
      out.write("		<span> 점</span>\r\n");
      out.write("      <span id=\"ratingDisplay\" class=\"hidden\"></span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 💬 댓글 입력창 -->\r\n");
      out.write("    <textarea id=\"revwriteSection\" name=\"content\" placeholder=\"리뷰를 입력해주세요.\" rows=\"3\"\r\n");
      out.write("      class=\"w-full border border-gray-300 rounded p-3 resize-none focus:outline-none focus:ring-1 focus:ring-primary text-sm\"></textarea>\r\n");
      out.write("\r\n");
      out.write("    <!-- 📎 파일 + 등록 버튼 -->\r\n");
      out.write("<div class=\"flex items-center justify-between gap-4 w-full\">\r\n");
      out.write("  <!-- 파일 선택 input -->\r\n");
      out.write("  <input\r\n");
      out.write("  type=\"file\"\r\n");
      out.write("  id=\"previewInput\"\r\n");
      out.write("  name=\"imageFile\"\r\n");
      out.write("  accept=\"image/*\"\r\n");
      out.write("  multiple\r\n");
      out.write("  class=\"block text-sm text-gray-500 file:mr-4 file:py-1 file:px-2 file:rounded file:border-0 file:text-sm file:font-semibold file:bg-primary/10 file:text-primary hover:file:bg-primary/20\"\r\n");
      out.write("/>\r\n");
      out.write("  <!-- 이미지 미리보기 (가로 정렬) -->\r\n");
      out.write("  <div id=\"previewContainer\" class=\"flex flex-wrap gap-2\"></div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 등록 버튼 -->\r\n");
      out.write("  <button type=\"submit\" class=\"bg-primary text-white px-4 py-2 rounded-md hover:bg-primary/90 whitespace-nowrap\">\r\n");
      out.write("    등록\r\n");
      out.write("  </button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("  <!-- ✅ 플로팅 챗봇 -->\r\n");
      out.write("  <div class=\"fixed bottom-6 right-6 z-50\">\r\n");
      out.write("    <button class=\"bg-primary text-white w-14 h-14 rounded-full shadow-lg flex items-center justify-center\">\r\n");
      out.write("      <i class=\"ri-message-3-line ri-lg\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("<div id=\"imageModal\" class=\"fixed inset-0 z-50  bg-neutral-800/50 backdrop-blur-sm hidden flex items-center justify-center text-white\">\r\n");
      out.write("  <div class=\"relative max-w-5xl w-full px-4\">\r\n");
      out.write("    <div class=\"relative overflow-hidden\">\r\n");
      out.write("      <img id=\"modalImage\" src=\"\" class=\"max-h-[70vh] mx-auto rounded-lg object-contain transition duration-300\" />\r\n");
      out.write("\r\n");
      out.write("      <!-- 좌우 화살표 -->\r\n");
      out.write("      <button id=\"prevBtn\" class=\"absolute top-1/2 left-0 transform -translate-y-1/2 text-white text-3xl px-4 hover:text-primary z-50\">&#10094;</button>\r\n");
      out.write("      <button id=\"nextBtn\" class=\"absolute top-1/2 right-0 transform -translate-y-1/2 text-white text-3xl px-4 hover:text-primary z-50\">&#10095;</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 📝 추가된 설명 영역 -->\r\n");
      out.write("    <div class=\"mt-4 text-center\">\r\n");
      out.write("       <p id=\"modalUser\" class=\"text-sm opacity-90\"></p>\r\n");
      out.write("   \r\n");
      out.write("    <p id=\"modalCreated\" class=\"text-xs mt-1 opacity-60\"></p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 닫기 -->\r\n");
      out.write("     <button onclick=\"closeImageModal()\" \r\n");
      out.write("            class=\"absolute -top-6 -right-6 bg-black/70 text-white w-10 h-10 rounded-full flex items-center justify-center hover:bg-red-600 z-50 shadow-lg transition\">\r\n");
      out.write("      <i class=\"ri-close-line text-xl\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"mainImageModal\" class=\"fixed inset-0 z-50 bg-black/70 backdrop-blur-sm hidden flex items-center justify-center text-white\">\r\n");
      out.write("  <div class=\"relative max-w-5xl w-full px-4\">\r\n");
      out.write("    <img id=\"mainModalImage\" class=\"max-h-[70vh] mx-auto rounded-lg object-contain transition duration-300\" />\r\n");
      out.write("    <button id=\"mainPrevBtn\" class=\"absolute top-1/2 left-0 transform -translate-y-1/2 text-white text-3xl px-4\">&#10094;</button>\r\n");
      out.write("    <button id=\"mainNextBtn\" class=\"absolute top-1/2 right-0 transform -translate-y-1/2 text-white text-3xl px-4\">&#10095;</button>\r\n");
      out.write("    <button onclick=\"closeMainImageModal()\" class=\"absolute top-4 right-4 bg-white/10 w-10 h-10 rounded-full flex items-center justify-center hover:bg-red-600\"><i class=\"ri-close-line text-xl\"></i></button>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"deleteModal\" class=\"fixed inset-0 bg-black/50 backdrop-blur-sm hidden flex items-center justify-center z-50\">\r\n");
      out.write("  <div class=\"bg-white rounded-lg p-6 w-full max-w-sm shadow-lg\">\r\n");
      out.write("    <h2 class=\"text-lg font-semibold text-gray-800 mb-4\">리뷰 삭제 확인</h2>\r\n");
      out.write("    <p class=\"text-sm text-gray-600 mb-2\">본인 확인을 위해 회원 ID를 입력하세요.</p>\r\n");
      out.write("    <input type=\"text\" id=\"deleteUserIdInput\" class=\"w-full border px-3 py-2 rounded text-sm mb-4\" placeholder=\"회원 ID 입력\" />\r\n");
      out.write("    <div class=\"flex justify-end gap-2\">\r\n");
      out.write("      <button onclick=\"closeDeleteModal()\" class=\"px-4 py-2 text-sm text-gray-600 hover:text-black\">취소</button>\r\n");
      out.write("      <button id=\"confirmDeleteBtn\" class=\"bg-gray-800 hover:bg-red-600 text-white px-4 py-2 text-sm rounded\">삭제</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"reportModal\" class=\"hidden fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50\">\r\n");
      out.write("  <div class=\"bg-white rounded-xl shadow p-6 w-80 space-y-4\">\r\n");
      out.write("    <h2 class=\"text-lg font-bold text-gray-800 text-center\">리뷰 신고</h2>\r\n");
      out.write("    <p class=\"text-sm text-gray-600 text-center\">정말 이 리뷰를 신고하시겠습니까?</p>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"flex justify-center gap-4 pt-2\">\r\n");
      out.write("      <button onclick=\"closeReportModal()\" class=\"px-4 py-2 rounded bg-gray-300 text-gray-800 text-sm\">취소</button>\r\n");
      out.write("      <button id=\"confirmReportBtn\" class=\"px-4 py-2 rounded bg-red-600 text-white text-sm\">신고</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"toast\"\r\n");
      out.write("     class=\"hidden fixed top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 \r\n");
      out.write("            bg-black bg-opacity-70 text-white px-4 py-2 rounded shadow z-50 \r\n");
      out.write("            opacity-0 transition-opacity duration-500 text-sm text-center max-w-[80%]\">\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/destinationdetail.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("loginUserId");
      // /WEB-INF/views/destinationdetail.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/destinationdetail.jsp(4,0) '${sessionScope.loginUser.userId}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.loginUser.userId}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/destinationdetail.jsp(237,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("review");
      // /WEB-INF/views/destinationdetail.jsp(237,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/destinationdetail.jsp(237,2) '${reviewList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${reviewList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    <div class=\"review-card bg-white shadow rounded-xl p-6 space-y-4 relative\" id=\"review-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\r\n");
            out.write("      <div class=\"view-mode space-y-2\">\r\n");
            out.write("  <!-- 상단: 회원 ID + 수정/삭제 -->\r\n");
            out.write("  <div class=\"flex justify-between items-start\">\r\n");
            out.write("    <div class=\"text-sm font-semibold text-gray-800\">회원 ID: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("    ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("  </div>\r\n");
            out.write("\r\n");
            out.write("  <!-- 이미지 -->\r\n");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("  <!-- 별점 -->\r\n");
            out.write("  <div class=\"flex text-yellow-400 text-base mt-2\">\r\n");
            out.write("    ");
            if (_jspx_meth_c_005fforEach_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("    ");
            if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("    ");
            if (_jspx_meth_c_005fforEach_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("  </div>\r\n");
            out.write("\r\n");
            out.write("  <!-- 내용 -->\r\n");
            out.write("  <p class=\"text-sm text-gray-900 whitespace-pre-line\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("\r\n");
            out.write("  <!-- 하단 작성일 + 추천 + 신고 -->\r\n");
            out.write("  <div class=\"flex justify-between items-center mt-2\">\r\n");
            out.write("    <p class=\"text-sm text-gray-400\">작성일: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.createdAt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("    <div class=\"flex items-center gap-2\">\r\n");
            out.write("      <button class=\"text-sm text-gray-500 hover:text-primary px-2 py-1 rounded-full border text-xs\">👍 추천</button>\r\n");
            out.write("      <button class=\"text-xs text-gray-400 hover:text-red-500\">신고</button>\r\n");
            out.write("    </div>\r\n");
            out.write("  </div>\r\n");
            out.write("</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("  <!-- 리뷰 내용 -->\r\n");
            out.write("  <p class=\"text-sm text-gray-900 whitespace-pre-line mt-1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("      <!-- ✅ 수정모드 -->\r\n");
            out.write("      <div class=\"edit-mode hidden\">\r\n");
            out.write("        <input type=\"number\" class=\"border rounded px-2 py-1 text-sm\" name=\"rating\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.rating}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" min=\"0\" max=\"5\" step=\"0.5\" />\r\n");
            out.write("        <textarea name=\"content\" class=\"w-full mt-2 border p-2 rounded text-sm\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</textarea>\r\n");
            out.write("\r\n");
            out.write("        <div class=\"grid grid-cols-2 gap-4 mt-3\" id=\"edit-images-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("          ");
            if (_jspx_meth_c_005fforEach_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("        </div>\r\n");
            out.write("        </div>\r\n");
            out.write("        <div class=\"mt-2\">\r\n");
            out.write("	  <label class=\"text-sm text-gray-600\">이미지 추가:</label>\r\n");
            out.write("<input type=\"file\" id=\"editFileInput\" name=\"newImageFiles\" multiple accept=\"image/*\"\r\n");
            out.write("  class=\"mt-1 block w-full text-sm border rounded p-1\" />\r\n");
            out.write("<div id=\"editPreviewContainer\" class=\"mt-4 grid grid-cols-2 gap-4\"></div>\r\n");
            out.write("	\r\n");
            out.write("\r\n");
            out.write("        <div class=\"mt-4 flex gap-2\">\r\n");
            out.write("          <button class=\"bg-primary text-white px-4 py-2 rounded text-sm\" onclick=\"submitReviewEdit(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\">완료</button>\r\n");
            out.write("          <button class=\"bg-gray-300 text-gray-700 px-4 py-2 rounded text-sm\" onclick=\"cancelReviewEdit(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\">취소</button>\r\n");
            out.write("        </div>\r\n");
            out.write("      </div>\r\n");
            out.write("    </div>\r\n");
            out.write("  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/destinationdetail.jsp(244,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.userId == loginUserId or review.userId eq loginUserId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <div class=\"flex gap-2\">\r\n");
          out.write("    <button onclick=\"editReview(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\"\r\n");
          out.write("            class=\"flex items-center gap-1 text-blue-600 hover:text-primary text-sm font-medium\">\r\n");
          out.write("      <img src=\"https://cdn-icons-png.flaticon.com/512/84/84380.png\" class=\"w-4 h-4\" />수정\r\n");
          out.write("    </button>\r\n");
          out.write("    <button onclick=\"deleteReview(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\"\r\n");
          out.write("            class=\"flex items-center gap-1 text-red-500 hover:text-red-700 text-sm font-medium\">\r\n");
          out.write("      <img src=\"https://cdn-icons-png.flaticon.com/512/6861/6861362.png\" class=\"w-4 h-4\" />삭제\r\n");
          out.write("    </button>\r\n");
          out.write("  </div>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/destinationdetail.jsp(259,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty review.imagePath and fn:length(review.imagePath) > 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <div class=\"grid grid-cols-2 gap-4 mt-2\">\r\n");
          out.write("  \r\n");
          out.write("    \r\n");
          out.write("    ");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("    \r\n");
          out.write("    ");
          if (_jspx_meth_c_005fforEach_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("    \r\n");
          out.write("  </div>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/destinationdetail.jsp(263,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("img");
      // /WEB-INF/views/destinationdetail.jsp(263,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/destinationdetail.jsp(263,4) '${fn:split(review.imagePath, ',')}'",_jsp_getExpressionFactory().createValueExpression(new org.apache.jasper.el.ELContextWrapper(_jspx_page_context.getELContext(),_jspx_fnmap_2),"${fn:split(review.imagePath, ',')}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/destinationdetail.jsp(263,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("      ");
            if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/destinationdetail.jsp(264,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index lt 2 and not empty img}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("             class=\"w-full h-[250px] object-cover rounded-xl shadow cursor-pointer review-image\"\r\n");
          out.write("             alt=\"리뷰 이미지\" />\r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/destinationdetail.jsp(272,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("img");
      // /WEB-INF/views/destinationdetail.jsp(272,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/destinationdetail.jsp(272,4) '${fn:split(review.imagePath, ',')}'",_jsp_getExpressionFactory().createValueExpression(new org.apache.jasper.el.ELContextWrapper(_jspx_page_context.getELContext(),_jspx_fnmap_2),"${fn:split(review.imagePath, ',')}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/destinationdetail.jsp(272,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("      ");
            if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\r\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /WEB-INF/views/destinationdetail.jsp(273,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index ge 2 and not empty img}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("             class=\"hidden review-image\"\r\n");
          out.write("             alt=\"리뷰 이미지 (숨김)\" />\r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/destinationdetail.jsp(286,4) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setBegin(1);
      // /WEB-INF/views/destinationdetail.jsp(286,4) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.fullStars}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<i class=\"ri-star-fill\"></i>");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/destinationdetail.jsp(287,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.halfStar}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<i class=\"ri-star-half-fill\"></i>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f4_reused = false;
    try {
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/destinationdetail.jsp(288,4) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setBegin(1);
      // /WEB-INF/views/destinationdetail.jsp(288,4) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.emptyStars}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<i class=\"ri-star-line\"></i>");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f4);
      _jspx_th_c_005fforEach_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f5_reused = false;
    try {
      _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/destinationdetail.jsp(316,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setVar("img");
      // /WEB-INF/views/destinationdetail.jsp(316,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/destinationdetail.jsp(316,10) '${fn:split(review.imagePath, ',')}'",_jsp_getExpressionFactory().createValueExpression(new org.apache.jasper.el.ELContextWrapper(_jspx_page_context.getELContext(),_jspx_fnmap_2),"${fn:split(review.imagePath, ',')}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
        if (_jspx_eval_c_005fforEach_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            ");
            if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fforEach_005f5, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f5))
              return true;
            out.write("\r\n");
            out.write("          ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f5);
      _jspx_th_c_005fforEach_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f5, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f5)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f5);
      // /WEB-INF/views/destinationdetail.jsp(317,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty img}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("              <div class=\"relative\">\r\n");
          out.write("                <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"w-full h-[250px] object-cover rounded shadow\" />\r\n");
          out.write("                <button type=\"button\"\r\n");
          out.write("                        onclick=\"this.closest('div').remove();\"\r\n");
          out.write("                        class=\"absolute top-2 right-2 bg-red-500 text-white w-6 h-6 rounded-full text-xs flex items-center justify-center\">×</button>\r\n");
          out.write("              </div>   \r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }
}
