/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2025-05-14 09:21:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class place_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1745564312942L));
    _jspx_dependants.put("jar:file:/D:/midProject_wk/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tripin/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Tripin - 여행지 검색</title>\r\n");
      out.write("<!-- css파일연결 -->\r\n");
      out.write("<link href=\"/tripin/resources/css/css_place_list.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Pacifico 폰트 링크 -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Pacifico&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Noto Sans KR 폰트 링크 -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&amp;display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Remix icon 아이콘 폰트 라이브러리 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.6.0/remixicon.min.css\">\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<!-- js파일 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tripin/resources/js/place_list.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- 헤더 -->\r\n");
      out.write("  <header class=\"place_list_header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <!-- 타이틀 -->\r\n");
      out.write("      <a href=\"#\" class=\"main_title\">Tripin</a> \r\n");
      out.write("      <nav>\r\n");
      out.write("      	<a href=\"#\" class=\"home\">홈</a>\r\n");
      out.write("      	<a href=\"#\" class=\"trivy\">트리비와 대화하기</a>\r\n");
      out.write("      	<a href=\"#\" class=\"theme\">테마여행</a>\r\n");
      out.write("      	<a href=\"#\" class=\"community\">커뮤니티</a>      \r\n");
      out.write("      </nav>		\r\n");
      out.write("      <div class=\"icon-group\">\r\n");
      out.write("        <button class=\"icon-button\">\r\n");
      out.write("          <i class=\"ri-user-line\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("  <!-- 메인 -->\r\n");
      out.write("  <main class=\"container column-layout\">\r\n");
      out.write("  <div>\r\n");
      out.write("  <!-- 검색창 -->\r\n");
      out.write("    <section class=\"search-section full-width\">\r\n");
      out.write("      <div class=\"search-box\">\r\n");
      out.write("        <div class=\"search-icon\">\r\n");
      out.write("          <i class=\"ri-search-line ri-lg\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input type=\"text\" class=\"search-input\" placeholder=\"여행지, 명소, 체험 검색\">\r\n");
      out.write("        <button class=\"search-button\">검색</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!-- 테마 필터 -->\r\n");
      out.write("  <div class=\"theme-filter-wrapper scroll-container\">\r\n");
      out.write("  	<div class=\"theme-filter-scroll\">\r\n");
      out.write("  		<button class=\"theme-button\">\r\n");
      out.write("  			<div class=\"theme-icon\">\r\n");
      out.write("  				<i class=\"ri-landscape-line ri-xl\"></i>\r\n");
      out.write("  			</div>\r\n");
      out.write("  			<span>자연</span>\r\n");
      out.write("  		</button>\r\n");
      out.write("  		<button class=\"theme-button\">\r\n");
      out.write("  			<div class=\"theme-icon\">\r\n");
      out.write("  				<i class=\"ri-ancient-pavilion-line ri-xl\"></i>\r\n");
      out.write("  			</div>\r\n");
      out.write("  			<span>문화</span>\r\n");
      out.write("  		</button>\r\n");
      out.write("  		<button class=\"theme-button\">\r\n");
      out.write("  			<div class=\"theme-icon\">\r\n");
      out.write("  				<i class=\"ri-run-line ri-xl\"></i>\r\n");
      out.write("  			</div>\r\n");
      out.write("  			<span>레저</span>\r\n");
      out.write("  		</button>\r\n");
      out.write("  		<button class=\"theme-button\">\r\n");
      out.write("  			<div class=\"theme-icon\">\r\n");
      out.write("  				<i class=\"ri-restaurant-line ri-xl\"></i>\r\n");
      out.write("  			</div>\r\n");
      out.write("  			<span>맛집</span>\r\n");
      out.write("  		</button>\r\n");
      out.write("  		<button class=\"theme-button\">\r\n");
      out.write("  			<div class=\"theme-icon\">\r\n");
      out.write("  				<i class=\"ri-hotel-line ri-xl\"></i>\r\n");
      out.write("  			</div>\r\n");
      out.write("  			<span>숙소</span>\r\n");
      out.write("  		</button>\r\n");
      out.write("  		<button class=\"theme-button\">\r\n");
      out.write("  			<div class=\"theme-icon\">\r\n");
      out.write("  				<i class=\"ri-shopping-bag-line ri-xl\"></i>\r\n");
      out.write("  			</div>\r\n");
      out.write("  			<span>쇼핑</span>\r\n");
      out.write("  		</button>\r\n");
      out.write("  		<button class=\"theme-button\">\r\n");
      out.write("  			<div class=\"theme-icon\">\r\n");
      out.write("  				<i class=\"ri-calendar-event-line ri-xl\"></i>\r\n");
      out.write("  			</div>\r\n");
      out.write("  			<span>축제</span>\r\n");
      out.write("  		</button>\r\n");
      out.write("  	</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!-- 필터옵션 -->\r\n");
      out.write("  <section class=\"filter-bar\">\r\n");
      out.write("  	<div class=\"filter-left\">\r\n");
      out.write("  		<span class=\"filter-label\">정렬기준 : </span>\r\n");
      out.write("  		<div class=\"sort-dropdown\">\r\n");
      out.write("  			<button class=\"sort-button\"  id=\"sort-button\">\r\n");
      out.write("  				<span id=\"selectedSort\">인기순</span> \r\n");
      out.write("  				<i class=\"ri-arrow-down-s-line\"></i>\r\n");
      out.write("  			</button>\r\n");
      out.write("  			<div class=\"dropdown-menu\" id=\"dropdown-menu\">\r\n");
      out.write("  				<div class=\"dropdown-item\" data-value=\"인기순\">인기순</div>\r\n");
      out.write("  				<div class=\"dropdown-item\" data-value=\"별점순\">별점순</div>\r\n");
      out.write("  				<div class=\"dropdown-item\" data-value=\"최신순\">최신순</div>  			\r\n");
      out.write("  			</div>\r\n");
      out.write("  		</div>\r\n");
      out.write("  		<div class=\"filter-tag\" data-value=\"자연\">\r\n");
      out.write("  			<span>자연</span>\r\n");
      out.write("  			<button class=\"filter-close\">\r\n");
      out.write("  				<i class=\"ri-close-line\"></i>\r\n");
      out.write("  			</button>\r\n");
      out.write("  		</div>\r\n");
      out.write("  	</div>\r\n");
      out.write("	<div class=\"filter-right\">\r\n");
      out.write("		<button class=\"reset-button\">\r\n");
      out.write("			<i class=\"ri-refresh-line reset-icon\"></i>\r\n");
      out.write("			<span>필터 초기화</span>\r\n");
      out.write("		</button>\r\n");
      out.write("	</div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- 검색 결과 목록 : db연결 -->\r\n");
      out.write("  <section class=\"result-bar\">\r\n");
      out.write("  	<!-- 여행지카드1 -->\r\n");
      out.write("  	<div class=\"place-card\">\r\n");
      out.write("  		<img  class=\"place-img\" \r\n");
      out.write("  		src=\"https://readdy.ai/api/search-image?query=Beautiful%20Jeju%20Island%20beach%20with%20volcanic%20rocks%2C%20clear%20blue%20water%2C%20and%20palm%20trees.%20Natural%20landscape%20with%20soft%20golden%20sand%20and%20blue%20sky%20with%20few%20clouds.%20Wide%20angle%20view%20of%20peaceful%20coastal%20scenery.&amp;width=600&amp;height=340&amp;seq=1&amp;orientation=landscape\" \r\n");
      out.write("  		alt=\"제주도 해변\">\r\n");
      out.write("  		<button class=\"bookmark\">\r\n");
      out.write("  			<i class=\"ri-heart-line\"></i>\r\n");
      out.write("  		</button>\r\n");
      out.write("  		<div class=\"place-content\">\r\n");
      out.write("  			<h3 class=\"place-title\">제주 협재 해변</h3>\r\n");
      out.write("  			<p class=\"place-text\">에메랄드 빛 바다와 하얀 모래사장이 어우러진 제주의 아름다운 해변</p>\r\n");
      out.write("  		</div>\r\n");
      out.write("  		<div class=\"place-info\">\r\n");
      out.write("            <div class=\"place-info-left\">\r\n");
      out.write("                <div class=\"map-pin\">\r\n");
      out.write("                    <i class=\"ri-map-pin-line\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span>제주시 한림읍 · 12.5km</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"place-info-right\">\r\n");
      out.write("                <div class=\"star\">\r\n");
      out.write("                    <i class=\"ri-star-fill\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"place-rate\">4.8</span>\r\n");
      out.write("                <span class=\"place-review-cnt\">(256)</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("  	</div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  </section>\r\n");
      out.write("  </main>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
